### PR TITLE
Require packages which work with Python2

### PR DESCRIPTION
**Pull request by ip1981**
Signed-off-by: Igor Pashev <pashev.igor@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2457)

### CODE REVIEW

**Comment by jgrund** [comment]
You need to update the lockfiles as well.

**Comment by ip1981** [comment]
I didn't see them used though.

**Comment by ip1981** [comment]
`Piplock` is a replacement for `requirements.txt` and we seem not using `Piplock`.

**Comment by jgrund** [comment]
we are using pipenv. You need to update the Pipfile and Pipfile.lock

**Comment by ip1981** [comment]
> we are using pipenv. You need to update the Pipfile and Pipfile.lock

Done. I was more worrying about building for production (which uses `requirements.txt`).

**Review by jgrund — CHANGES_REQUESTED** [review]
Looks like python unit tests are now failing due to a change in bandit

**Comment by ip1981** [comment]
Not needed.

**Pull request closed without merging**
