### PR TITLE
Update calculation of free/used space in IML CLI

### LINKED ISSUE #1770: Update calculation of free/used space in IML CLI
Calculation of free/used space in IML CLI should be updated like in GUI to be consistent => https://github.com/whamcloud/integrated-manager-for-lustre/pull/1694/commits/756e3b3400c86102513e68ec050a4a62ab890ac6

### PR DESCRIPTION
**Pull request by ip1981**
Make it show the same data as in GUI. Closes #1770.

**Before:**
```
+------+-----------+------------------+---------+---------+------+------+
| Name | State     | Space            | Inodes  | Clients | MDTs | OSTs |
+------+-----------+------------------+---------+---------+------+------+
| fs   | available | 333 MiB / 46 GiB | 3K / 3M | 0       | 2    | 10   |
+------+-----------+------------------+---------+---------+------+------+
| fs2  | available | 332 MiB / 46 GiB | 3K / 3M | 0       | 1    | 10   |
+------+-----------+------------------+---------+---------+------+------+
```

**After:**
```
+------+-----------+------------------+-------------------+---------+------+------+
| Name | State     | Space Used/Avail | Inodes Used/Avail | Clients | MDTs | OSTs |
+------+-----------+------------------+-------------------+---------+------+------+
| fs   | available | 333 MiB / 43 GiB | 3K / 3M           | 0       | 2    | 10   |
+------+-----------+------------------+-------------------+---------+------+------+
| fs2  | available | 332 MiB / 43 GiB | 3K / 3M           | 0       | 1    | 10   |
+------+-----------+------------------+-------------------+---------+------+------+
```

Signed-off-by: Igor Pashev <pashev.igor@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1803)

### CODE REVIEW

**Comment by ip1981** [comment]
> What's the difference between bytes_total and bytes_avail?

that's a good question :)

Doc - 20-4-20 - 14-47 - p1

**Comment by ip1981** [comment]
Maybe we are still doing it wrong in GUI (and dashboards). There is a possibility that "used" becomes greater than "available".

**Comment by ip1981** [comment]
> What's the difference between bytes_total and bytes_avail

After some pondering, I think a more interesting question is the difference between "free" and "available"  :) It looks like _free_ is the difference between _total_ and existing files, _available_ is the difference between _total_ and all files plus some system overhead. And thus _free_ = _available_ + overhead.

**Comment by johnsonw** [comment]
@ip1981 I received a somewhat related question recently in regards to `lfs -df` output. Have you found any information about this in the lustre docs by any chance? I know we've discussed this before and it wasn't documented. How did you come up with ` free = available + overhead`?

**Comment by jgrund** [comment]
> And thus free = available + overhead. 

Except for ZFS I think. 

It debatable which one to use, but available is what can actually be used by a user and seems like the correct choice.

**Comment by ip1981** [comment]
> @ip1981 I received a somewhat related question recently in regards to `lfs -df` output. Have you found any information about this in the lustre docs by any chance? I know we've discussed this before and it wasn't documented. How did you come up with ` free = available + overhead`?

Oh, it is simple:

1 A fresh FS, with some space used initially (N bytes).
2. Fill the FS with files, watch how _total_ is constant, but _free_ and _avail_ are reducing.
3. See the difference between _free_ and _avail_ which is those N bytes :)

**Pull request merged**
