### PR TITLE
Jobstats: Do not return empty list when only one point fall in range

### PR DESCRIPTION
**Pull request by AlexTalker**
Hello again

The problem in this case that if only one value is returned from the model,
and `rate` operator specified(which is default for `fetch_jobs`), then related "Jobstats" page
says that no data is available.

However, that's not true.

In any way, you seem to have strange representation of timestamps since on the server side they tend to change up to 10 seconds and highly depend on client-side time, which is strange since you do display charts correctly BUT the user may not find associated `Jobstats` by clicking on the heat-map chart, since the values falls out of transformed `begin` and `end` range.
Also, hell knows why you do not show target names on the chart but the `PK` instead.

### CODE REVIEW

**Comment by AlexTalker** [comment]
Shrinking the time window breaks correlation between the data and timestamps shown in the `GUI`.
You probably might want to round both arguments but I changed only existing approach.

**Comment by AlexTalker** [comment]
@jgrund @utopiabound Would you kindly review this one?

**Comment by AlexTalker** [comment]
Actually, skipping subtraction was a bad idea for `/ui/jobstats` route, since it were a bit confused by incoming data and showed invalid values.
So I reverted this approach and just keep the time window intact instead.

**Comment by jgrund** [comment]
test this please

**Comment by jgrund** [comment]
test this please

**Comment by jgrund** [comment]
test this please

**Comment by AlexTalker** [comment]
@jgrund Could you do something about the tests?
Just for the note, I go to the test page, the only indicator for me is status of this PR.

**Pull request merged**
