### PR TITLE
Add LNet action plugins

### PR DESCRIPTION
**Pull request by johnsonw**
Create LNet action plugins to be invoked in the rust agent.

Signed-off-by: johnsonw <wjohnson@whamcloud.com>

---
This change is [Reviewable](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2427)

### CODE REVIEW

**Review by jgrund — CHANGES_REQUESTED** [review]
A few things need to be updated.

1. All commands should use `.kill_on_drop(true)`
1. Move over the existing comments from the Python impl to this one, they looked like they were useful.
1. `configure_lnet` is missing from this impl. Instead of the modprobe stuff it did before it should use dynamic lnet configuration https://wiki.lustre.org/Dynamic_LNet_Configuration_and_lnetctl

**Review by nlinker — COMMENTED** [review]
Do you have the examples of the rest calls to test it locally against vagrant VMs?

**Comment by johnsonw** [comment]
@nlinker these will be added in a separate patch.

**Review by jgrund — CHANGES_REQUESTED** [review]
This PR needs to be moved.

**Pull request closed without merging**
