### PR TITLE
Fix Stat deletion

### LINKED ISSUE #2258: target table dropping filesystem names
The `target` table intermittently drops filesystem names from targets:

Screen Shot 2020-09-21 at 1 13 22 PM

Notice the MGS has no filesystems in the second query.

Some matching debug:

```
Sep 21 18:12:21 adm iml-device: #033[2mSep 21 18:12:21.989#033[0m #033[34mDEBUG#033[0m iml_device: target_to_fs: {"fs-OST0006": [(Fqdn("oss2.local"), "fs")], "fs-OST0003": [(Fqdn("oss1.local"), "fs")], "fs-OST0001": [(Fqdn("oss1.local"), "fs")], "fs-OST0005": [(Fqdn("oss1.local"), "fs")], "fs-OST0008": [(Fqdn("oss2.local"), "fs")], "fs-OST0007": [(Fqdn("oss1.local"), "fs")], "fs-OST0002": [(Fqdn("oss2.local"), "fs")], "fs-OST0000": [(Fqdn("oss2.local"), "fs")], "fs-MDT0001": [(Fqdn("mds2.local"), "fs")], "fs-MDT0000": [(Fqdn("mds1.local"), "fs")], "fs-OST0004": [(Fqdn("oss2.local"), "fs")], "fs-OST0009": [(Fqdn("oss1.local"), "fs")]}
Sep 21 18:12:22 adm iml-device: #033[2mSep 21 18:12:21.999#033[0m #033[34mDEBUG#033[0m iml_device: target_to_fs: {"MGS": [(Fqdn("mds2.local"), "fs")]}
Sep 21 18:13:16 adm iml-device: #033[2mSep 21 18:13:16.969#033[0m #033[34mDEBUG#033[0m iml_device: target_to_fs: {"fs-OST0009": [(Fqdn("oss1.local"), "fs")], "fs-OST0006": [(Fqdn("oss2.local"), "fs")], "fs-OST0007": [(Fqdn("oss1.local"), "fs")], "fs-OST0003": [(Fqdn("oss1.local"), "fs")], "fs-OST0001": [(Fqdn("oss1.local"), "fs")], "fs-OST0004": [(Fqdn("oss2.local"), "fs")], "fs-OST0005": [(Fqdn("oss1.local"), "fs")], "fs-MDT0000": [(Fqdn("mds1.local"), "fs")], "fs-OST0000": [(Fqdn("oss2.local"), "fs")], "fs-OST0008": [(Fqdn("oss2.local"), "fs")], "fs-OST0002": [(Fqdn("oss2.local"), "fs")], "fs-MDT0001": [(Fqdn("mds2.local"), "fs")]}
Sep 21 18:13:16 adm iml-device: #033[2mSep 21 18:13:16.979#033[0m #033[34mDEBUG#033[0m iml_device: target_to_fs: {}
```

The empty HashMap corresponds to the influx query here: https://github.com/whamcloud/integrated-manager-for-lustre/blob/5da2d3032fd8099d58a29e884c7ee26fcfea6086/iml-services/iml-device/src/lib.rs#L574-L580

### PR DESCRIPTION
**Pull request by jgrund**
The current targets table is intermittently losing it's filesystems for
some targets.

This appears to be because we delete stat info before inserting the next
batch. If anyone queries during this gap, they will get empty data even
though we have the points, they just haven't been inserted yet.

In addition, we are clearing out all stats except a single point for any target colocated on the MGS node.

This patch waits until after insertion to do a deletion, and scopes the
delete so it should only effect the correct stat.

Fixes #2258.

Signed-off-by: Joe Grund <jgrund@whamcloud.io>

---
This change is [Reviewable](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2263)

### CODE REVIEW

**Review by johnsonw — APPROVED** [review]

**Review by mkpankov — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2263)* status: all files reviewed, 2 unresolved discussions (waiting on @jgrund)

___
*[iml-services/iml-stats/src/main.rs, line 496 at r1](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2263#-MHtrLy-59LReSS9t3s6:-MHtrLy-59LReSS9t3s7:b-4vn83h) ([raw file](https://github.com/whamcloud/integrated-manager-for-lustre/blob/1b4365926d88d690633d86ee4eaeb2b8df0e986e/iml-services/iml-stats/src/main.rs#L496)):*
> ```Rust
>         let entries: Vec<_> = xs
>             .into_iter()
>             .inspect(|x| {
> ```

I'd expect `inspect` to not mutate, maybe `map`?
___
*[iml-services/iml-stats/src/main.rs, line 551 at r1](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2263#-MHtrtsPEyL6th25-WkE:-MHtrtsPEyL6th25-WkF:bmoc7hl) ([raw file](https://github.com/whamcloud/integrated-manager-for-lustre/blob/1b4365926d88d690633d86ee4eaeb2b8df0e986e/iml-services/iml-stats/src/main.rs#L551)):*
> ```Rust
>             WHERE mgs_fs='{}' AND is_mgs_fs=true
>             ORDER BY time ASC
>             LIMIT 2"#,
> ```

Why `LIMIT 2`?

**Comment by jgrund** [comment]
___
*[iml-services/iml-stats/src/main.rs, line 496 at r1](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2263#-MHtrLy-59LReSS9t3s6:-MHv1xhYEiMRN_g0rKFQ:b-axwbs4) ([raw file](https://github.com/whamcloud/integrated-manager-for-lustre/blob/1b4365926d88d690633d86ee4eaeb2b8df0e986e/iml-services/iml-stats/src/main.rs#L496)):*
<details><summary><i>Previously, mkpankov (Michael Pankov) wrote…</i></summary><blockquote>

I'd expect `inspect` to not mutate, maybe `map`?
</blockquote></details>

it is not mutating the contained value, it's purely there for the side-effect of mutating fs_names, which is not associated with the combinator.
Using `map` would indicate the contained value is being mutated, which isn't the case here.

**Comment by jgrund** [comment]
___
*[iml-services/iml-stats/src/main.rs, line 551 at r1](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2263#-MHtrtsPEyL6th25-WkE:-MHv2Kvv1h5a_d6hoYpR:bhgil3g) ([raw file](https://github.com/whamcloud/integrated-manager-for-lustre/blob/1b4365926d88d690633d86ee4eaeb2b8df0e986e/iml-services/iml-stats/src/main.rs#L551)):*
<details><summary><i>Previously, mkpankov (Michael Pankov) wrote…</i></summary><blockquote>

Why `LIMIT 2`?
</blockquote></details>

because if there is 1 or 0 it's a noop.

**Review by johnsonw — APPROVED** [review]

**Review by mkpankov — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2263)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
