### PR TITLE
Assign values directly instead of mem::replace

### PR DESCRIPTION
**Pull request by mkpankov**
Fixes the warnings in the agent

Signed-off-by: Michael Pankov <work@michaelpankov.com>

---
This change is [Reviewable](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2108)

### CODE REVIEW

**Comment by ip1981** [comment]
Did you check it works in VM? I remember there was something weird.

**Comment by mkpankov** [comment]
@ip1981 well all the tests have passed, should be ok

**Comment by jgrund** [comment]
This is fixed on master with `let _` assignments

**Comment by mkpankov** [comment]
@jgrund this is based on master

Did you mean this PR?
https://github.com/whamcloud/integrated-manager-for-lustre/pull/2081

It only fixed this in `iml-gui`.

**Comment by mkpankov** [comment]
Nevermind

**Comment by ip1981** [comment]
> @ip1981 well all the tests have passed, should be ok

The tests are just approximation to the reality :D

**Pull request closed without merging**
