### PR TITLE
Fixed NID without network ID for all types of networks

### PR DESCRIPTION
**Pull request by AlexTalker**
Comparison [here](https://github.com/AlexTalker/integrated-manager-for-lustre/blob/master/chroma_core/lib/detection.py#L237) fails if I have an `InfiniBand` interface utilized by `LNet`.
This happens because `normalize_nid` doesn't act the same as the [agent](https://github.com/whamcloud/iml-agent/blob/master/chroma_agent/device_plugins/linux_network.py#L248).
Example of such metadata for `MGS`:
```
# tunefs.lustre --dryrun /dev/l_mgs 
checking for existing Lustre data: found
Reading CONFIGS/mountdata

   Read previous values:
Target:     MGS
Index:      unassigned
Lustre FS:  
Mount type: ldiskfs
Flags:      0x1004
              (MGS no_primnode )
Persistent mount opts: user_xattr,errors=remount-ro
Parameters:    failover.node=:10.239.239.1@o2ib:10.239.239.2@o2ib


   Permanent disk data:
Target:     MGS
Index:      unassigned
Lustre FS:  
Mount type: ldiskfs
Flags:      0x1004
              (MGS no_primnode )
Persistent mount opts: user_xattr,errors=remount-ro
Parameters:    failover.node=:10.239.239.1@o2ib:10.239.239.2@o2ib

exiting before disk write.
```

@jgrund @utopiabound Would you kindly review this one?

### CODE REVIEW

**Comment by jgrund** [comment]
test this please

**Comment by AlexTalker** [comment]
@jgrund I should note that even if I change the metadata with `tunefs.lustre` to contain `0`, it still removes it, which was described for `tcp` case in the function

**Comment by AlexTalker** [comment]
Does the testing takes forever? 😞

**Comment by jgrund** [comment]
@AlexTalker Shouldn't take this long, I'll take a look.

**Comment by AlexTalker** [comment]
Well, you definitely need to do something about the tests.
If you need any help from my side, just say.
I'm not authorized to see what is it in your Jenkins takes so long, so I can't do much.

**Comment by AlexTalker** [comment]
@jgrund @johnsonw @utopiabound Well, folks, it seems you have serious problems with checks status update here. Travic CI seems to have finished first step successfully https://travis-ci.com/whamcloud/integrated-manager-for-lustre/builds/99304352 but PR doesn't represent that.
I would appreciate if this fix will be merged into the mainstream as soon as possible and I tried escape possible regression in it.
This all takes too long which makes me kinda sad.

**Comment by jgrund** [comment]
The travis report looks like a github integration bug.

On the Jenkins front, We've exposed the results of testing to the public. We currently have some intermittent testing issues, most of which are documented as issues in this repo.

We're slowly getting through them, but of course any help is appreciated.

**Comment by AlexTalker** [comment]
@jgrund well, I do understand you situation but I'm not very familiar with your software and have other priorities right now.
Besides, you seems to have no troubles with merging other PRs, so I see no point why this tiny change shall be kept in queue any more.
So, I would highly appreciate if you'll finally resolve this one.

**Comment by jgrund** [comment]
@AlexTalker The latest SSI (shared-storage integration) testing run has an error around the area the change was made: https://build.whamcloud.com/job/integration-tests-shared-storage-configuration/1002/arch=x86_64,distro=el7,label=IML/testReport/junit/tests.integration.shared_storage_configuration.test_lnet_functionality/TestLNetFunctionality/test_nids/.

Need to investigate whether it's related to this change.

**Comment by jgrund** [comment]
test this please

**Pull request merged**
