### PR TITLE
Update iml-request-retry to pass iteration index

### PR DESCRIPTION
**Pull request by johnsonw**
There may be a case in which the future factory may need to generate a
different future based on the incremented tries. For example, if there
are two url's that can be fetched for the same information but the first
url fails, we should retry using the second url. If both of the urls are
stored in a vec, then this becomes trivial to fetch using the
incrementing index.

Signed-off-by: johnsonw <wjohnson@whamcloud.com>

---
This change is [Reviewable](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1959)

### CODE REVIEW

**Comment by jgrund** [comment]
@johnsonw needs more `rustfmt`

**Comment by jgrund** [comment]
Should the count be 1 indexed instead of 0 indexed?

**Comment by johnsonw** [comment]
Before the change it was 0 based so I figured I would keep it there. It works good for zero-based structures like vecs too but if you think it should start with 1 I can change it.

**Comment by nlinker** [comment]
I think the documentation on this (i.e. README.md) needs a bit of update, also it needs to emphasize how it is different from `retry_future_gen` (it accepts also `Fn(request_no, E) -> ...` function). The extension itself is good, since we often rely on the request numbers.

**Pull request merged**
