### PR TITLE
Implement Auth

### PR DESCRIPTION
**Pull request by jgrund**
This patch implements the auth layer for the iml-gui.

  - Implement Login page.
  - Implement auth module.
  - Add login / logout link and user link.
  - Add a number of extension traits in their own module.
  - Add a module to sleep for n milliseconds with a cancel handle.
  - Add a global sink.

## Login Flow:

login-flow

## Logout flow

logout-flow
  
## Restrict components to given user-level

restrict-component 

Signed-off-by: Joe Grund <jgrund@whamcloud.io>

---
This change is [Reviewable](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1525)

### CODE REVIEW

**Comment by nlinker** [comment]
___
*[iml-gui/crate/src/auth.rs, line 108 at r1](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1525#-LzcN-0nBcWdCAojhm6l:-LzcN-0nBcWdCAojhm6m:bjanzkv) ([raw file](https://github.com/whamcloud/integrated-manager-for-lustre/blob/41916c202d55d4fadac163a12f70c74103e4d40f/iml-gui/crate/src/auth.rs#L108)):*
> ```Rust
> 
> pub(crate) fn fetch_session() -> fetch::Request {
>     fetch::Request::api_call(Session::endpoint_name()).with_auth()
> ```

Could you give me a pointer, how does it treat errors? I mean in case of success, `seed` emits `Msg::Fetched`, but in case of a failure?

**Comment by nlinker** [comment]
___
*[iml-gui/crate/src/auth.rs, line 89 at r1](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1525#-LzcQhE712Dpur3UmWwo:-LzcQhE80EmNTLMVx4pu:b-q5ld6h) ([raw file](https://github.com/whamcloud/integrated-manager-for-lustre/blob/41916c202d55d4fadac163a12f70c74103e4d40f/iml-gui/crate/src/auth.rs#L89)):*
> ```Rust
>             }
> 
>             let (cancel, fut) = sleep_with_handle(10_000, Msg::Fetch, Msg::Noop);
> ```

10000 of what? seconds? milliseconds?

**Comment by jgrund** [comment]
___
*[iml-gui/crate/src/auth.rs, line 89 at r1](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1525#-LzcQhE712Dpur3UmWwo:-LzciopZEiwJF27BGXfh:b-bx588f) ([raw file](https://github.com/whamcloud/integrated-manager-for-lustre/blob/41916c202d55d4fadac163a12f70c74103e4d40f/iml-gui/crate/src/auth.rs#L89)):*
<details><summary><i>Previously, nlinker (Nick Linker) wrote…</i></summary><blockquote>

10000 of what? seconds? milliseconds?
</blockquote></details>

yeah, milliseconds. I'll have it take a duration.

**Comment by jgrund** [comment]
___
*[iml-gui/crate/src/auth.rs, line 108 at r1](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1525#-LzcN-0nBcWdCAojhm6l:-Lzcj6nZ5QWSt2xfiqhY:bfya8rn) ([raw file](https://github.com/whamcloud/integrated-manager-for-lustre/blob/41916c202d55d4fadac163a12f70c74103e4d40f/iml-gui/crate/src/auth.rs#L108)):*
<details><summary><i>Previously, nlinker (Nick Linker) wrote…</i></summary><blockquote>

Could you give me a pointer, how does it treat errors? I mean in case of success, `seed` emits `Msg::Fetched`, but in case of a failure?
</blockquote></details>

It depends on what method is called, but in general the return is type `Result<T, T>`. Ex: https://docs.rs/seed/0.5.1/seed/browser/service/fetch/struct.Request.html#method.fetch_json_data.

It does it this way so the same `Msg` is called in either case and handle success error in one spot.

**Comment by jgrund** [comment]
___
*[iml-wire-types/wire-types.rs, line 1087 at r1](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1525#-LzcRhj8A__Y57CIvz5Q:-LzcjbP27AmAWfjdtsx1:b-clkbw7) ([raw file](https://github.com/whamcloud/integrated-manager-for-lustre/blob/41916c202d55d4fadac163a12f70c74103e4d40f/iml-wire-types/wire-types.rs#L1087)):*
<details><summary><i>Previously, nlinker (Nick Linker) wrote…</i></summary><blockquote>

Where is the API described/implemented?
</blockquote></details>

Code is underhttps://github.com/whamcloud/integrated-manager-for-lustre/tree/master/chroma_api for now. High level description is here: https://whamcloud.github.io/Online-Help/docs/api/rest_API.html

**Comment by jgrund** [comment]
___
*[iml-gui/crate/src/auth.rs, line 89 at r1](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1525#-LzcQhE712Dpur3UmWwo:-Lzh41RI2FIf2jtkogGR:b-896fix) ([raw file](https://github.com/whamcloud/integrated-manager-for-lustre/blob/41916c202d55d4fadac163a12f70c74103e4d40f/iml-gui/crate/src/auth.rs#L89)):*
<details><summary><i>Previously, jgrund (Joe Grund) wrote…</i></summary><blockquote>

yeah, milliseconds. I'll have it take a duration.
</blockquote></details>

Done.

**Pull request merged**
