### PR TITLE
Use IML cli inside iml-timer

### PR DESCRIPTION
**Pull request by jgrund**
The iml-timer service currently uses it's own internal CLI for stratagem
scans instead of reusing the iml cli.

If we follow this pattern, it will mean we need to create a separate
binary for each service we want to run as a timer inside of docker.

Instead, we should embed the iml cli inside the container and call it
the same way we do outside the container.

This will allow us to write a single cli command for running snapshot
commands instead of having to maintain two commands.

Signed-off-by: Joe Grund <jgrund@whamcloud.io>

---
This change is [Reviewable](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2202)

### CODE REVIEW

**Comment by johnsonw** [comment]
I've been testing this on a cluster and it looks like everything is working as expected. I ssh'd into the docker `iml-timer` container and was able to schedule an interval. 

```
[root@iml-timer /]# iml <service> interval add --filesystem fs --interval 2m
✔ Configuring <service> scan interval successful

[root@iml-timer /]# systemctl list-timers --all
NEXT                         LEFT         LAST                         PASSED    UNIT                         ACTIVATE
S
Tue 2020-09-01 20:32:49 UTC  1min 9s left n/a                          n/a       iml-<service>-1.timer        iml-<service>-1.service
Wed 2020-09-02 20:07:43 UTC  23h left     Tue 2020-09-01 20:07:43 UTC  23min ago systemd-tmpfiles-clean.timer systemd-
tmpfiles-clean.service
n/a                          n/a          n/a                          n/a       systemd-readahead-done.timer systemd-
readahead-done.service
```

**Comment by jgrund** [comment]
> I've been testing this on a cluster and it looks like everything is working as expected. 

Does it work as expected when you schedule it via the GUI? And does everything work correctly when the timer fires?

**Comment by johnsonw** [comment]
The test I just completed involved scheduling the timer using the iml cli inside the iml-timer container. I scheduled the timer after creating a variety of different sized files on the mounted client. After the interval completed I checked the fs detail page and the charts had populated as expected. I will now remove the timer using the cli and then add the timer back using the gui.

**Comment by johnsonw** [comment]
Removing the timer:
```
[root@iml-timer /]# iml <service> interval remove --filesystem fs
✔ Remove <service> for the given filesystem successful
[root@iml-timer /]# systemctl list-timers --all
NEXT                         LEFT     LAST                         PASSED    UNIT                         ACTIVATES
Wed 2020-09-02 20:07:43 UTC  23h left Tue 2020-09-01 20:07:43 UTC  33min ago systemd-tmpfiles-clean.timer systemd-tmpf
iles-clean.service
n/a                          n/a      n/a                          n/a       systemd-readahead-done.timer systemd-read
ahead-done.service
```

**Comment by johnsonw** [comment]
After the interval was removed I waited several minutes to make sure the data didn't update. I then removed some of the files and scheduled a new interval using the gui. After the interval ticket the charts reflected the new change. Checking the timer on the iml-timer container:
```
[root@iml-timer /]# systemctl list-timers --all
NEXT                         LEFT     LAST                         PASSED       UNIT                         ACTIVATES
Tue 2020-09-01 21:08:50 UTC  31s left Tue 2020-09-01 21:06:50 UTC  1min 28s ago iml-<service>-2.timer        iml-<service>-2.service
Wed 2020-09-02 20:07:43 UTC  22h left Tue 2020-09-01 20:07:43 UTC  1h 0min ago  systemd-tmpfiles-clean.timer systemd-t
mpfiles-clean.service
n/a                          n/a      n/a                          n/a          systemd-readahead-done.timer systemd-r
eadahead-done.service

3 timers listed.
```

**Review by mkpankov — APPROVED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2202)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jgrund)

**Review by ip1981 — APPROVED** [review]

**Pull request merged**
