### PR TITLE
Reenable job_scheduler/host tests

### PR DESCRIPTION
**Pull request by mkpankov**
Signed-off-by: Michael Pankov <work@michaelpankov.com>

### CODE REVIEW

**Comment by mkpankov** [comment]
So here's our failure I found locally:
https://travis-ci.com/whamcloud/integrated-manager-for-lustre/jobs/270667248#L2962

Any pointers to where to fix that?

**Comment by ip1981** [comment]
> Empty file has been added only?
> How does it fix the issue?

It's Python :)

**Comment by ip1981** [comment]
I think the problem is somewhere around here => https://github.com/whamcloud/integrated-manager-for-lustre/blob/25b89153a863cbee7527ce01e742ca14c91cdbda/chroma_core/models/host.py#L72

The `hosts` argument is passed to `__init__`, it does not accept it.

**Comment by mkpankov** [comment]
@nlinker `__init__.py` marks a "regular package", somewhat akin to `mod.rs`. [Details](https://stackoverflow.com/a/448279)

**Comment by jgrund** [comment]
There were actually a number of errors in these tests. Are all fixed now.

**Pull request merged**
