### PR TITLE
Use direct lctl device calls for snapshots

### PR DESCRIPTION
**Pull request by jgrund**
Signed-off-by: Joe Grund <jgrund@whamcloud.io>

---
This change is [Reviewable](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2364)

### CODE REVIEW

**Comment by johnsonw** [comment]
```
[root@adm tmp]# iml snapshot list fs
+------------+----------+---------------------------------+-----------+---------+
| Filesystem | Snapshot | Creation Time                   | State     | Comment |
+============+==========+=================================+===========+=========+
| fs         | test     | Fri, 06 Nov 2020 22:54:55 +0000 | unmounted | ---     |
+------------+----------+---------------------------------+-----------+---------+

[root@mds1 ~]# iml-agent snapshot list fs-MDT0000
[Snapshot { filesystem_name: "fs", snapshot_name: "test", snapshot_fsname: "2c1accd5", modify_time: 2020-11-06T22:54:55Z, create_time: 2020-11-06T22:54:55Z, mounted: false, comment: None }]

[root@adm tmp]# iml snapshot destroy fs test
[1/1]   ✔ Destroying snapshot successful
[root@adm tmp]# iml snapshot list fs

[root@adm tmp]#
```

image

**Comment by johnsonw** [comment]
This is mostly working, but I see one problem still. When going from `unmounted` to `mounted`, the iml-agent will show this properly but it is not propagated up to the manager and reflected in the database. It may have something to do with how the daemon is working. I'm currently investigating.

**Comment by johnsonw** [comment]
The snapshot mounting is now being reflected correctly:
```
[root@adm tmp]# iml snapshot list fs
+------------+----------+---------------------------------+---------+---------+
| Filesystem | Snapshot | Creation Time                   | State   | Comment |
+============+==========+=================================+=========+=========+
| fs         | test     | Tue, 10 Nov 2020 22:19:27 +0000 | mounted | ---     |
+------------+----------+---------------------------------+---------+---------+
```

**Comment by johnsonw** [comment]
Testing update:

```
chroma=> select * from snapshot;
 id | filesystem_name | snapshot_name |      create_time       |      modify_time       | snapshot_fsname | mounted | comment
----+-----------------+---------------+------------------------+------------------------+-----------------+---------+---------
  1 | fs              | test          | 2020-11-11 21:12:28+00 | 2020-11-11 21:12:28+00 | 7c30140b        | t       |
(1 row)

chroma=> \q
[root@adm tmp]# iml snapshot list fs
+------------+----------+---------------------------------+---------+---------+
| Filesystem | Snapshot | Creation Time                   | State   | Comment |
+============+==========+=================================+=========+=========+
| fs         | test     | Wed, 11 Nov 2020 21:12:28 +0000 | mounted | ---     |
+------------+----------+---------------------------------+---------+---------+

[root@adm tmp]# iml snapshot unmount fs test
[1/1]   ✔ Unmounting snapshot successful

...

[root@adm tmp]# iml snapshot list fs
+------------+----------+---------------------------------+-----------+---------+
| Filesystem | Snapshot | Creation Time                   | State     | Comment |
+============+==========+=================================+===========+=========+
| fs         | test     | Wed, 11 Nov 2020 21:12:28 +0000 | unmounted | ---     |
+------------+----------+---------------------------------+-----------+---------+
```

**Comment by johnsonw** [comment]
Testing with multiple snapshots:

```
[root@adm tmp]# iml snapshot create fs test2
[1/1]   ✔ Creating snapshot successful
[root@adm tmp]# iml snapshot list fs
+------------+----------+---------------------------------+-----------+---------+
| Filesystem | Snapshot | Creation Time                   | State     | Comment |
+============+==========+=================================+===========+=========+
| fs         | test     | Wed, 11 Nov 2020 21:12:28 +0000 | unmounted | ---     |
+------------+----------+---------------------------------+-----------+---------+
| fs         | test2    | Wed, 11 Nov 2020 21:43:16 +0000 | unmounted |         |
+------------+----------+---------------------------------+-----------+---------+

[root@adm tmp]# iml snapshot mount fs test2
[1/1]   ✔ Mounting snapshot successful
[root@adm tmp]# iml snapshot list fs
+------------+----------+---------------------------------+-----------+---------+
| Filesystem | Snapshot | Creation Time                   | State     | Comment |
+============+==========+=================================+===========+=========+
| fs         | test     | Wed, 11 Nov 2020 21:12:28 +0000 | unmounted | ---     |
+------------+----------+---------------------------------+-----------+---------+
| fs         | test2    | Wed, 11 Nov 2020 21:43:16 +0000 | mounted   |         |
+------------+----------+---------------------------------+-----------+---------+

[root@adm tmp]# iml snapshot create fs2 test3
[1/1]   ✔ Creating snapshot successful
[root@adm tmp]# iml snapshot list fs
+------------+----------+---------------------------------+-----------+---------+
| Filesystem | Snapshot | Creation Time                   | State     | Comment |
+============+==========+=================================+===========+=========+
| fs         | test     | Wed, 11 Nov 2020 21:12:28 +0000 | unmounted | ---     |
+------------+----------+---------------------------------+-----------+---------+
| fs         | test2    | Wed, 11 Nov 2020 21:43:16 +0000 | mounted   |         |
+------------+----------+---------------------------------+-----------+---------+

[root@adm tmp]# iml snapshot list fs2
+------------+----------+---------------------------------+-----------+---------+
| Filesystem | Snapshot | Creation Time                   | State     | Comment |
+============+==========+=================================+===========+=========+
| fs2        | test3    | Wed, 11 Nov 2020 21:44:26 +0000 | unmounted | ---     |
+------------+----------+---------------------------------+-----------+---------+

[root@adm tmp]# iml snapshot mount fs2 test3
[1/1]   ✔ Mounting snapshot successful
[root@adm tmp]# iml snapshot list fs2
+------------+----------+---------------------------------+---------+---------+
| Filesystem | Snapshot | Creation Time                   | State   | Comment |
+============+==========+=================================+=========+=========+
| fs2        | test3    | Wed, 11 Nov 2020 21:44:26 +0000 | mounted | ---     |
+------------+----------+---------------------------------+---------+---------+

[root@adm tmp]# iml snapshot list fs2
+------------+----------+---------------------------------+---------+---------+
| Filesystem | Snapshot | Creation Time                   | State   | Comment |
+============+==========+=================================+=========+=========+
| fs2        | test3    | Wed, 11 Nov 2020 21:44:26 +0000 | mounted | ---     |
+------------+----------+---------------------------------+---------+---------+

[root@adm tmp]# iml snapshot unmount fs2 test3
[1/1]   ✔ Unmounting snapshot successful
[root@adm tmp]# iml snapshot destroy fs2 test3
[1/1]   ✔ Destroying snapshot successful
[root@adm tmp]# iml snapshot create fs2 test
[1/1]   ✔ Creating snapshot successful
[root@adm tmp]# iml snapshot list fs2
+------------+----------+---------------------------------+-----------+---------+
| Filesystem | Snapshot | Creation Time                   | State     | Comment |
+============+==========+=================================+===========+=========+
| fs2        | test     | Wed, 11 Nov 2020 21:51:37 +0000 | unmounted | ---     |
+------------+----------+---------------------------------+-----------+---------+

[root@adm tmp]# iml snapshot mount fs2 test
[1/1]   ✔ Mounting snapshot successful
[root@adm tmp]# iml snapshot list fs2
+------------+----------+---------------------------------+---------+---------+
| Filesystem | Snapshot | Creation Time                   | State   | Comment |
+============+==========+=================================+=========+=========+
| fs2        | test     | Wed, 11 Nov 2020 21:51:37 +0000 | mounted | ---     |
+------------+----------+---------------------------------+---------+---------+
```

**Comment by johnsonw** [comment]
Test rebuilding in 2893.

**Review by nlinker — COMMENTED** [review]
> Reviewed 4 of 7 files at r1, 6 of 8 files at r2, 2 of 2 files at r4, 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2364)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnsonw)

**Review by johnsonw — APPROVED** [review]

**Pull request merged**
