### PR TITLE
Trim down docker image size

### PR DESCRIPTION
**Pull request by jgrund**
Signed-off-by: Joe Grund <jgrund@whamcloud.io>

### CODE REVIEW

**Comment by ip1981** [comment]
I wonder if it could be possible to use white listing instead of black listing (.dockerignore).

**Comment by jgrund** [comment]
It looks like `*` followed by a number of `!...` lines can be used to simulate whitelisting.

**Comment by jgrund** [comment]
I think for now we can stick to a blacklist as this is basically working.

**Comment by jgrund** [comment]
> What are the numbers before and after?

I'll post after it publishes to docker-hub, but I think it was ~ 80MB.

**Pull request merged**
