### PR TITLE
Fix table formatting

### LINKED ISSUE #1107: Fix table formatting on fs detail page
The length of the volume name in each table is different, which shifts the entries in the table a bit. We should fix the widths in the table cells to ensure the tables columns are aligned properly.

### PR DESCRIPTION
**Pull request by johnsonw**
Fixes #1107.

Signed-off-by: Will Johnson <wjohnson@whamcloud.com>

### CODE REVIEW

**Comment by johnsonw** [comment]
image

image

**Comment by jgrund** [comment]
Is the Volume label for the MGS being truncated?

**Comment by johnsonw** [comment]
I intentionally removed a good portion of the string to show that the tables are still in alignment.

**Comment by johnsonw** [comment]
The second image shows that the primary and secondary columns are not being displayed.

**Comment by jgrund** [comment]
According to mdn, break-word is deprecated: https://developer.mozilla.org/en-US/docs/Web/CSS/word-break

**Comment by johnsonw** [comment]
Looks like I can use "break-all"

**Pull request merged**
